#!/bin/bash

# Create Client Script
# Usage: ./create-client.sh client-name

set -e

if [ $# -eq 0 ]; then
    echo "Usage: $0 <client-name>"
    echo "Example: $0 my-awesome-client"
    exit 1
fi

CLIENT_NAME=$1
CLIENT_DIR="clients/$CLIENT_NAME"

# Check if client already exists
if [ -d "$CLIENT_DIR" ]; then
    echo "Error: Client '$CLIENT_NAME' already exists!"
    exit 1
fi

echo "🚀 Creating new client: $CLIENT_NAME"

# Create client directory structure
mkdir -p "$CLIENT_DIR"/{src/app,src/components,public/assets}

# Copy template files (you would need to create these templates)
echo "📋 Setting up project structure..."

# Create package.json
cat > "$CLIENT_DIR/package.json" << EOF
{
  "name": "$CLIENT_NAME",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "14.0.0",
    "react": "^18",
    "react-dom": "^18",
    "framer-motion": "^12.0.0",
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "typescript": "^5",
    "tailwindcss": "^3.3.0",
    "autoprefixer": "^10.0.1",
    "eslint": "^8",
    "eslint-config-next": "14.0.0"
  }
}
EOF

# Create next.config.ts
cat > "$CLIENT_DIR/next.config.ts" << EOF
import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  experimental: {
    appDir: true,
  },
  images: {
    domains: ['localhost'],
  },
};

export default nextConfig;
EOF

# Create tailwind.config.ts
cat > "$CLIENT_DIR/tailwind.config.ts" << EOF
import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'brand-primary': '#your-primary-color',
        'brand-secondary': '#your-secondary-color',
      },
      fontFamily: {
        'sans': ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
export default config
EOF

# Create tsconfig.json
cat > "$CLIENT_DIR/tsconfig.json" << EOF
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "es6"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
EOF

# Create basic layout
cat > "$CLIENT_DIR/src/app/layout.tsx" << EOF
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: '$CLIENT_NAME',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
EOF

# Create basic page
cat > "$CLIENT_DIR/src/app/page.tsx" << EOF
export default function Home() {
  return (
    <main className="min-h-screen flex items-center justify-center">
      <div className="text-center">
        <h1 className="text-4xl font-bold mb-4">Welcome to $CLIENT_NAME</h1>
        <p className="text-lg text-gray-600">Your project is ready to build!</p>
      </div>
    </main>
  )
}
EOF

# Create globals.css
cat > "$CLIENT_DIR/src/app/globals.css" << EOF
@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --foreground-rgb: 0, 0, 0;
  --background-start-rgb: 214, 219, 220;
  --background-end-rgb: 255, 255, 255;
}

@media (prefers-color-scheme: dark) {
  :root {
    --foreground-rgb: 255, 255, 255;
    --background-start-rgb: 0, 0, 0;
    --background-end-rgb: 0, 0, 0;
  }
}

body {
  color: rgb(var(--foreground-rgb));
  background: linear-gradient(
      to bottom,
      transparent,
      rgb(var(--background-end-rgb))
    )
    rgb(var(--background-start-rgb));
}
EOF

# Create .gitignore
cat > "$CLIENT_DIR/.gitignore" << EOF
# See https://help.github.com/articles/ignoring-files/ for more about ignoring files.

# dependencies
/node_modules
/.pnp
.pnp.js

# testing
/coverage

# next.js
/.next/
/out/

# production
/build

# misc
.DS_Store
*.pem

# debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# local env files
.env*.local

# vercel
.vercel

# typescript
*.tsbuildinfo
next-env.d.ts
EOF

# Create README
cat > "$CLIENT_DIR/README.md" << EOF
# $CLIENT_NAME

A Next.js project for $CLIENT_NAME.

## Getting Started

First, install dependencies:

\`\`\`bash
npm install
\`\`\`

Then, run the development server:

\`\`\`bash
npm run dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000) with your browser to see the result.

## Project Structure

- \`src/app/\` - Next.js app router pages
- \`src/components/\` - React components
- \`public/\` - Static assets

## Deployment

Deploy to Vercel by connecting your GitHub repository.

For more information, see the [Next.js documentation](https://nextjs.org/docs).
EOF

echo "✅ Client '$CLIENT_NAME' created successfully!"
echo ""
echo "Next steps:"
echo "1. cd $CLIENT_DIR"
echo "2. npm install"
echo "3. npm run dev"
echo "4. Start building your components in src/components/"
echo ""
echo "Happy coding! 🎉"